from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from .apis import (
                    style_number_create,
                    get_latest_style_number,
                    article_number_create,
                    get_latest_article_number,
                    corporate_all_products,
                    ware_house_create,
                    store_create,
                    
                    ws_product_transfer,
                    ws_inward_area_list,
                    ws_tranfer_area_list,
                    ws_product_inward_accept,
                    
                    store_product_transfer_request,
                    create_customer,
                    create_store_employee, 
                    customer_check_out,
                    get_customer_purchase_history,
                    get_employe_list,
                    get_store_invoice_list,
                    get_store_details,
                    create_credit_note,
                    get_store_credit_notes_list,
                    create_credit_redeem,
                    get_store_credit_redeem_list,
                    get_credit_Item_detail,
                    hold_item,
                    get_store_hold_items,
                    retrive_hold_item,
                    send_report,
                    get_last_invoice,
                    get_last_credit_number,
                    
                    check_username,
                    check_credit_number,
                    LoginApi,
                    CustomObtainAuthToken,
                    get_store_product_transfer_request,
                    store_accept_product,
                    get_store_products,
                    get_all_store_emps,
                    edit_customer_details,
                    get_all_invoice_list,
                    )
                   
urlpatterns = [
     url(r'^authenticate/', CustomObtainAuthToken.as_view()),
     url('style-number-create/', style_number_create, name='style-number-create'),
     url('get-latest-style-number/', get_latest_style_number, name='get-latest-style-number'),
     url('article-number-create/', article_number_create, name='article-number-create'),
     url('get-latest-article-number/', get_latest_article_number, name='get-latest-article-number'),
     url('corporate-all-products/', corporate_all_products, name='corporate-all-products'),
     url('ware-house-create/', ware_house_create, name='ware-house-create'),
     url('store-create/', get_all_invoice_list, name='all-invoices'),
         url('all-invoices/', store_create, name='store-create'),
     url('get-store-products/', get_store_products, name='get_store_products'),
     url('ws-product-transfer/', ws_product_transfer, name='ws_product_transfer'),
     url('store-accpet-product/', store_accept_product, name='store_accept_product'),
     url('store-product-transfer-request/', store_product_transfer_request, name='store_product_transfer_request'),
     url('get_store_product_transfer_request/', get_store_product_transfer_request, name='get_store_product_transfer_request'),
     url('ws-inward-area-list/', ws_inward_area_list, name='ws-inward-area-list'),
     url('ws-tranfer-area-list/', ws_tranfer_area_list, name='ws-tranfer-area-list'),
     url('ws-product-inward-accept/', ws_product_inward_accept, name='ws-product-inward-accept'),

     url('create-customer/', create_customer, name='create-customer'),
     url('edit-customer-details/', edit_customer_details, name='edit_customer_details'),
     url('create-store-employee/', create_store_employee, name='create-store-employee'),
     url('customer-check-out/', customer_check_out, name='customer-checkout'),
     url('get-customer-purchase-history/', get_customer_purchase_history, name='get-customer-purchase-history'),
     url('employee-list/', get_employe_list, name='get-employe-list'),
     url('invoice-list/', get_store_invoice_list, name='get-store-invoice-list'),
     url('store-details/', get_store_details, name='get-store-details'),
     url('get-all-store-emps/', get_all_store_emps, name='get_all_store_emps'),
     url('create-credit-note/', create_credit_note, name='create_credit_note'),
     url('store-credit-notes/$', get_store_credit_notes_list, name='store-credit-notes'),
     url('create-credit-redeem/$', create_credit_redeem, name='create-credit-redeem'),
     url('store-credit-redeems/$', get_store_credit_redeem_list, name='store-credit-redeem'),
     url('store-credit-notes/(?P<credit_number>\d+)/$', get_credit_Item_detail, name='store-credit-details'),
     url('add-hold-item/', hold_item, name='hold-item'),
     url('hold-items-list/', get_store_hold_items, name='hold-items-list'),
     url('retrive-items-list/', retrive_hold_item, name='retrive-items-list'),
     url('send-report/', send_report, name='send-report'),
     url('get_last_invoice/', get_last_invoice, name='get_last_invoice'),
     url('get_last_credit_number/', get_last_credit_number, name='get_last_credit_number'),

     url('check-credit-number/', check_credit_number, name='check_credit_number'),
     url('check-user-name/', check_username, name='check_user_name'),
     url("^auth/login/$", LoginApi.as_view(), name='user_login'),

]

urlpatterns = format_suffix_patterns(urlpatterns)                   